# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1a70aa334e71d417342677f5862730f517dfda77764bf815d51c7d5e19f31a8590720d97c0909ec686252dde689e2c3b65a38a94cd18c7b51056e46e8b039a2e

test:
  secret_key_base: f9ad4c84cff864c2f1dc63a232562efb88a9ca565f6ad3228af0a09cb632ebbd13372843751edc6899d7bb84ed684e3dd1e671e649dabdbccb49fbd7635c4675

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
